app:
    build: app
    container_name: rpsls_app
    tty: true
    volumes:
        - ./code/symfony:/var/www/symfony
        - ./share/logs/symfony:/var/www/symfony/app/logs
        - ./share/logs/nginx:/var/log/nginx

db:
    container_name: rpsls_mongo
    image: mongo:2.6
    ports:
        - 28000:27017
    volumes_from:
        - app

php:
    build: php-fpm
    container_name: rpsls_php
    links:
        - db
    ports:
        - 9000:9000
    volumes_from:
        - app

nginx:
    build: nginx
    container_name: rpsls_nginx
    links:
        - "db:database"
        - php
    ports:
        - 80:80
    volumes_from:
        - app
