app:
    build: app
    container_name: mmp_app
    tty: true
    volumes:
        - ./code/symfony:/var/www/symfony
        - ./share/cache:/var/www/symfony/app/cache
        - ./share/images:/var/www/symfony/web/images
        - ./share/logs/symfony:/var/www/symfony/app/logs
        - ./share/fonts:/var/www/symfony/web/fonts
        - ./share/logs/nginx:/var/log/nginx
        - ./share/sessions:/var/lib/php5/sessions

db:
    container_name: mmp_mongo
    image: mongo:2.6
    ports:
        - 28000:27017
    volumes_from:
        - app

php:
    build: php-fpm
    container_name: mmp_php
    links:
        - db
    ports:
        - 9000:9000
    volumes_from:
        - app

nginx:
    build: nginx
    container_name: mmp_nginx
    links:
        - "db:database"
        - php
    ports:
        - 80:80
    volumes_from:
        - app
